Embedding Images and Video - First Pull Request
anapdh/youtube-clone pull request #2
Opened 2020-09-22 19:57 UTC by anapdh

The first pull request for code review.

2020-09-22 20:57 UTC, teekaytech requested changes
# Status: Changes Required :recycle: 

### Hello team :wave: ;

**You've started the project well. However, a lot of changes are required before this project can be approved. Please review the points below carefully and make all the changes as required.**

**[REQUIRED CHANGES]**
_These changes must be made before the project can be approved._

- [ ] Your project structure and layout does not look like the original page structure.

- Here's the original youtube video player page, from [this url](http://archive.vn/Bss88)

![o](https://user-images.githubusercontent.com/26856491/93935390-71e58400-fd1c-11ea-8286-d166eadc776a.png)

- Here's your own youtube player page: 

![y](https://user-images.githubusercontent.com/26856491/93935480-9a6d7e00-fd1c-11ea-8b4d-686fd7f41bf4.png)

You are expected to produce a clone of the original page. Please study the original page carefully and make your layout/design to conform with it.

- [ ] Your pull request description does not summarize the changes you're trying to merge. 
- Your pull request description should be a summary of the changes you're willing to merge to master.

![o](https://user-images.githubusercontent.com/26856491/93935739-00f29c00-fd1d-11ea-8c6f-68b5af2ba6ae.png)

- [ ] Most of the images you referenced in your project (index.html) are not rendering. Please take some time to read and understand the requirements of this project, then make changes where necessary.

- [ ] You did not follow CSS best practices.
- I observed that you use IDs a lot as your CSS selector. You should get used to using class names as CSS selectors.
- Please take a step back and review [this lesson](https://speckyboy.com/good-bad-css-practices) on CSS good and bad practices. 

![o](https://user-images.githubusercontent.com/26856491/93936117-93933b00-fd1d-11ea-98ae-428a0b28913f.png)

- [ ] Kindly check the highlighted points I made in your code and fix them.

**Please make these changes and request for another review by submitting a new code review request form when you are done.**

I'm @taofeekolalere on slack, in case you need further clarification.
Happy coding :man_technologist:

2020-09-22 20:57 UTC, teekaytech commented on README.md
> +
Your live demo link is not working. Kindly replace it when you're done making all the other changes. [This link](https://rawcdn.githack.com/) might help you.

2020-09-22 20:57 UTC, teekaytech commented on styles.css
> +  height: 60%;
Be consistent with your spaces and tabs. Kindly fix this section and other sections of your CSS rules that are not well indented

2020-09-22 20:57 UTC, teekaytech commented on styles.css
> +}
You should always specify the unit when declaring CSS rules that deal with measurement. e.g. `width: 100%` or `width: 100px`, etc.

2020-09-22 20:57 UTC, teekaytech commented on styles.css
> +}
You have some repeated code in these blocks. Always try to keep your code DRY. Please try to refactor these blocks.

2020-09-22 20:57 UTC, teekaytech commented on styles.css
> +*/
Always delete commented code / block of codes. Please remove this block.
![1](https://user-images.githubusercontent.com/26856491/93934450-1797f380-fd1b-11ea-8831-4678d0e75fe8.png)

2020-09-22 20:57 UTC, teekaytech commented on styles.css
> +  left: 0;*/
Delete this too.

2020-09-22 20:57 UTC, teekaytech commented on styles.css
> +  right: 0;*/
Please delete this too.

2020-09-22 20:57 UTC, teekaytech commented on youtube-homepage.html
> +      <p>---------------------------------------------------------------------------------------------</p>
This is not a good practice. You can use an horizontal line `<hr>` for this. You just style it up with your CSS to look like this. Besides, I'm not sure this is in the project.

2020-09-23 21:20 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Good work on implementing the requested changes. However, there are a few more changes needed:**

# Mandatory

1).  **You are not allowed to use screenshots/image for the image side text on the sidebar(check the circled area on the image below). Please use HTML tags to add the side texts and ensure the styling and alignment is similar to the original page.**

- [ ] Ensure that students do not use screenshots of original page as shortcut to bypass requirements. 

![youtube_clone_sideimage](https://user-images.githubusercontent.com/38922385/94067271-4c2cad80-fdf6-11ea-8bf3-5c58a11097b0.png)

2). **The section below the  video does not look like the original.**

original  |  clone
---------- | ---------
![bottom_original](https://user-images.githubusercontent.com/38922385/94068379-c6116680-fdf7-11ea-8ae3-0388d4681c74.png)  |  ![bottom_clone](https://user-images.githubusercontent.com/38922385/94068420-d1649200-fdf7-11ea-9b07-270c289ab254.png)

- Notice the subscribe button is displaying on the left and shows number of subscribers next to it.

- likes, dislikes and share icons display below the user avatar and subscribe button.

- The total number of views display on the right.

3). **The side text for the user avatar should not be a screenshot/image(check circled area on the image below). Use HTML to add the text and ensure the styling and alignment is similar to the original.**

![avatar1](https://user-images.githubusercontent.com/38922385/94069566-792e8f80-fdf9-11ea-8108-78a718eca14d.png)

4). **Add a Getting started section, on your read me file, with details on how to set up your project locally, and the necessary tools required.  Check the [readme](https://github.com/microverseinc/readme-template) template for more info on this.**

**There is one more comment below.**

# Optional

- **Fix the warnings from HTML checker.**

### Goodluck😃!

**PS: You can reach me on slack(Rose Wanjohi)**

2020-09-23 21:20 UTC, ghost commented on styles.css
> +  padding: 1294 x 1298;
The value of the padding property is not declared properly on line 3.  Check out this[ link](https://developer.mozilla.org/en-US/docs/Web/CSS/padding) on how to write and use the padding property.

2020-09-26 00:43 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-26 00:55 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [ ] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/94326247-35d04e80-ffbc-11ea-8567-9bf75c152b26.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/) ([screenshot](https://user-images.githubusercontent.com/29689273/94326203-fa358480-ffbb-11ea-81ec-b2704fb93212.png) from Pathwright)

- **Hint:** By closing `div` and `article` tags the issue will be fixed
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-26 19:37 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**There is one change that you have implemented as requested previously. Please check the comment below.**

**While at it, you can also fix the issue page link and mit link on your read me file.**

#### Happy coding guys!

**PS: You can reach me on slack(Rose Wanjohi).**

2020-09-26 19:37 UTC, blackpintz commented on styles.css
> +  padding: 1294 x 1298;
> The value of the padding property is not declared properly on line 3. Check out this[ link](https://developer.mozilla.org/en-US/docs/Web/CSS/padding) on how to write and use the padding property.

2020-09-26 23:03 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hi, @anapdh and @shahnaeem 
Congratulations on the work done so far, you guys are amazing. I see you have implemented most of the changes requested by the TSEs 👏 👏  👏 .

Let us quickly add some finishing touches, then we will be done.

- [ ] You still have one HTML validation errors. Use [validator.w3.org ](https://validator.w3.org/)

- [ ] Please refer to the last fix requested by the previous TSE. 
<img width="826" alt="Screen Shot 2020-09-26 at 11 59 00 PM" src="https://user-images.githubusercontent.com/5264771/94351736-5815ab00-0054-11eb-9591-92a3054d4927.png">

That is it guys, make these changes and you should be good to go.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-09-27 11:12 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

You can merge to master.
Good luck with your next project.

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

2020-09-27 11:17 UTC, merged